# Generated by Django 4.2.20 on 2025-04-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='An optional image representing the course.', null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the course was created.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the course was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='A detailed description of the course content.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_id',
            field=models.IntegerField(help_text='ID of the user instructing the course. Consider using a ForeignKey to the User model.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Flag indicating if the course has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the course.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='The current status of the course (e.g., Active, Inactive).', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='The title of the course.', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the course was last updated.'),
        ),
    ]
