# Generated by Django 4.2.20 on 2025-04-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_remove_course_image_url_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(help_text='The user designated as the instructor for this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the course has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', help_text='The current status of the course (e.g., Draft, Active, Inactive).', max_length=10),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='courses_cou_instruc_d2e347_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_deleted', 'deleted_at'], name='courses_cou_is_dele_423813_idx'),
        ),
    ]
